### ISSUE TITLE
It would be cool to traverse the "webring" in a game-like way 

### ISSUE THREAD

**Issue by mfekadu** [jskjott/webring#10]
## Context
So, right now if a user on a webring-member's site clicks the RC icon, then they will go to webring.recurse.com. That's cool. Next, if you want to **_explore_** the webring you just arbitrarily click other links, but it's not a **_ring_**

## Idea
Create a method for a webring-visitor to choose to **_explore the ring_** in a particular pattern (e.g., ring or a zigzag or whatever).

**How would it work?**
* User clicks `explore` and then gets to choose a pattern
  * circle
  * etc
* Then the user is transported/teleported/redirected to any arbitrary webring site.
* Then the user must find the RC logo on that site.
* Then the user must click the logo.
* Now, when the user is redirected back to Webring; Webring will prompt the user if they want to keep traversing the path/pattern. Also, Webring will let them know where they are in that pattern with some visualization. So, Webring is smart enough to further redirect the user to another Webring site, according to the chosen pattern. There could also be a countdown until an automatic redirection as well as a cancel/opt-out button. If it's been a while since the user last visited then there might not be an automatic redirection. Perhaps Webring could say "Hey, long time no see, buddy! Did you want to keep traversing the sites in a <pattern> pattern?"

**Tools and Tech?**
* Cookies to know the user
* HTML redirects
* Javascript alert/prompt & some CSS magic
* [localStorage][1] to know where the user is in the chosen pattern.
  * perhaps Cookies are not needed if localStorage is used?

**Edge Cases**
* What happens if a user travels back to Webring without the RC icon redirect?
  * should they restart?
  * should they keep going?
* What happens if it's been a long time (10 minutes? 30min? 1 hour? 1 day? 1 month?) since they last traversed the Webring
* What if the webring is updated in the middle of traveling? - @evanercolano
  * probably okay because it's just a bigger array yeah

## A Minimum Viable Product (Ring)
- [x] Use [Window.localStorage][1] to _remember_ the visited sites so far.
- [x] _Prompt_ the user if they want to keep traveling
- [x] _Redirect_ the user to the next path in the ring 

@jskjott 
@catilac
@Chatha-Sphere 

[1]: https://developer.mozilla.org/en/docs/Web/API/Window/localStorage

**Comment by mfekadu** [comment]
#12 resolved MVP, but would be cool to make it fancier!

**Comment by jskjott** [comment]
I just pushed a commit improving the UI of the explore functionality. Let me know what you think :)
