### ISSUE TITLE
where is webring go

### ISSUE THREAD

**Issue by lukeburns** [jskjott/webring#22]
:( :(

<img width="1075" alt="Screen Shot 2020-06-07 at 10 32 13 AM" src="https://user-images.githubusercontent.com/189068/83975729-28c30e80-a8aa-11ea-8acb-82e3b9ca0771.png">

**Comment by jskjott** [comment]
Thanks for flagging this - It should now be back up! 
I forgot to consider the webring when I was making some changes to the Github pages hosting setup.

**Comment by lukeburns** [comment]
wonderful, thx for the quick response!
